name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ~/Android/Sdk
    steps:
      - name: update tailscale version
        id: ver
        run: |
          tag=$(curl -s 'https://api.github.com/repos/tailscale/tailscale-android/releases/latest' | jq '.tag_name')
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "Using release: $tag"
      - name: android sdk check
        run: |
          echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          echo "ANDROID_HOME: $ANDROID_HOME"


